export default {
  products: [
    {
      _id: '111111111111111111111111',
      name: 'Nicho bonito',
      category: 'Nichos',
      image: '/images/product-1.jpg',
      price: 59,
      brand: 'MEOW',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Arranhador grande',
      category: 'Arranhadores',
      image: '/images/product-2.jpg',
      price: 70,
      brand: 'MiauBR',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'Nicho composto',
      category: 'Nichos',
      image: '/images/product-3.jpg',
      price: 59,
      brand: 'MEOW',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'Nicho acolchoado',
      category: 'Nichos',
      image: '/images/product-4.jpg',
      price: 90,
      brand: 'GatinhoFeliz',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Caminha pequena',
      category: 'Caminhas',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'MiauBR',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Brinquedinho Peixe',
      category: 'Brinquedos',
      image: '/images/product-6.jpg',
      price: 85,
      brand: 'Miau',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
